config/routes.rb
Rails.application.routes.draw do
	resources :playlist
	resources :playlist_song

	  get '/about' => 'page#about'

  root 'playlist#index'

end

app/models/helper.rb
class Helper
	def self.to_mins_dec secs
		secs / 60.0
	end

	def self.to_mins_s secs
		mins = secs / 60
		secs = secs % 60
		"#{mins}:#{secs}"
	end
end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
	def songs
		PlaylistSong.where(playlist_id:self.id)
	end
end

app/models/playlist_song.rb
gem 'rspotify'

class PlaylistSong < ActiveRecord::Base
	belongs_to :playlist

	def get
		RSpotify::Track.find(self.song_uid)
	end
	
	def image
		get.album.images[0]["url"]
	end

	def preview
		get.preview_url
	end

	def duration_secs
		get.duration_ms/1000
	end

	def duration_mins_dec
		Helper.to_mins_dec duration_secs
	end

	def duration_mins_s
		Helper.to_mins_s duration_secs
	end

	def spotify
		get.external_urls["spotify"]
	end
end

app/models/playlist_style.rb
class PlaylistStyle < ActiveRecord::Base
  belongs_to :playlist
end

app/models/spotify.rb
class Spotify 
	@spotify = RSpotify::Track
	def self.search params
		search_results = @spotify.search params
		results = []

		for track in search_results
			track_info = {}
			track_info[:name] = track.name
			track_info[:album] = track.album.name
			track_info[:artist] = track.artists[0].name
			track_info[:rank] = track.popularity
			track_info[:uid] = track.id
			results << track_info
		end

		results
	end

	# feelin' lucky search
	def self.lucky name
		search = (@spotify.search name).first
		result = {}
		result[:name] = search.name
		result[:album] = search.album.name
		result[:artist] = search.artists[0].name
		result[:rank] = search.popularity
		result[:uid] = search.id
		result
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/page_controller.rb
class PageController < ApplicationController

  def about
    
  end

end

app/controllers/playlist_controller.rb
class PlaylistController < ApplicationController
                
	# playlist#index is the current root route
        def index
        end

        def new
		# create a new blank playlist
                playlist = Playlist.create
                redirect_to edit_playlist_path playlist
        end

        def edit
		# get relevant playlist
                @playlist = Playlist.find params[:id]

		# update style record if such paramaters exist
                if params[:style]
			# create a new playlist_style record where none exists
                        if PlaylistStyle.where(playlist_id:@playlist.id).count == 0
                                playlist_style = PlaylistStyle.new
                                playlist_style.playlist_id = @playlist.id
			# otherwise get existing record
			else
				playlist_style = PlaylistStyle.where(playlist_id:@playlist.id)
			end

			# set playlist_style properties and save
			playlist_style.background_color = params[:style][:bgcolor]
			playlist_style.color = params[:style][:color]
			playlist_style.save
                end

		# set title
                if params[:playlist]
                        @playlist.title = params[:playlist][:title]
                        @playlist.save
                end

                @playlist.title == nil ? @title = "Untitled" : @title = @playlist.title

		# add new song to playlist
                if params[:new_song]
			# new blank song
                        song= PlaylistSong.new
			# set song title
			song.song_title = params[:new_song][:song_title]
			# get lucky with spotify
			song_spotify = Spotify.lucky song.song_title 
			# set remaining song properties and save
                        song.playlist_id = @playlist.id
                        song.artist_name = song_spotify[:artist] 
			song.song_uid = song_spotify[:uid]
			song.spotify_index = 0
                        song.save
                end

		# gather all songs for current playlist
                @songs = @playlist.songs
        end

        def show
		# get relevant playlist
                @playlist = Playlist.find params[:id]

		# gather songs for playlist
                @songs = PlaylistSong.where(playlist_id: @playlist.id).order('created_at DESC')

		# initialize empty array for collecting song uids
                @songs_uid = []

		# iterate over playlist songs
                for song in @songs
			# tell spotify that you're feelin' lucky
                        spotify = Spotify.lucky "#{song.song_title}"

			#update song properties based on spotify result and save
                        song.song_uid = spotify[:uid] 
                        song.artist_name = spotify[:artist]
                        song.save

			# add song uid to array
                        @songs_uid << song.song_uid
                end

		# join song uids as list_of_songs
                @list_of_songs = @songs_uid.join(",")

                if params[:notes] != nil
                        @songs.notes = params[:notes]
                end
        end 

        def destroy
		# get relevant playlist and destroy
                @playlist = Playlist.find params[:id]
                @songs = PlaylistSong.where(playlist_id: @playlist)
                
                for song in @songs
                        song.destroy
                end
                
                @playlist.destroy
                redirect_to root_path
        end
end

app/controllers/playlist_song_controller.rb
class PlaylistSongController < ApplicationController

	def edit
		# get song
		@song = PlaylistSong.find params[:id]

		# if loop for fix artist
		if params[:commit] = "Fix Artist"
			# get song
			@song = PlaylistSong.find params[:song_id]
			# advance spotify song index 
			@song.spotify_index += 1 
			# get songs from spotify
			songs_spotify = Spotify.search @song.song_title
			# get song at spotify_song_index
			song_spotify = songs_spotify[@song.spotify_index]
			# continue steping thru until new artist found
			until song_spotify[:artist] != @song.artist_name do
				# advance spotify song index
				@song.spotify_index += 1
				# get next spotify song
				song_spotify = songs_spotify[@song.spotify_index]
			end
			# update song artist and save
			@song.artist_name = song_spotify[:artist]
			@song.save
		end
		
		# if loop for add note
		
		# if loop for style note
		#render plain: params.inspect
		redirect_to edit_playlist_path(Playlist.find(@song.playlist_id))
	end

	def update
		@song = PlaylistSong.find params[:id]
		@song.notes = params[:notes]
		@song.save
		redirect_to playlist_path @song.playlist_id
	end

	def destroy
		@song = PlaylistSong.find params[:id]
		@song.destroy
		redirect_to "/playlist/#{@song.playlist_id}"
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/playlist_helper.rb
module PlaylistHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tapedeck</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css"> -->
  <%= csrf_meta_tags %>
</head>
<body>
  <!-- <div class="mxtp-container"> -->
  <header class="main-header">
    <h1 class="landing-title"><a href="/">MXTP</a></h1><span class="nav-links"><%= link_to "ABOUT", about_path %><%= link_to "GET STARTED", new_playlist_path %></span>
    <div class="diagonal-stripes"></div>
  </header>
    <%= yield %>

  </div>

</body>
</html>

app/views/page/about.html.erb
<div class="mxtp-main">
  <div class="about-section">
  <h1>About MXTP</h1>
  <hr>
    <p>
      Ever just listened to a song and just felt all the 'feels'?
    </p>
    <p>
      Yeah, us too! 
    </p>
    <p>
      Now you can share the feels with your partner or friends through MXTP!
    </p>
    <p>
      Just like an old school mixtape, MXTP allows you to collate all your favourite tracks into a playlist to send to your friend/partner/dog/cat/dinosaur etc... You can add notes like "Remember that time when..." or "This song reminds me of you because..."
    </p>
    <p>
      So what are you waiting for? Go ahead and get started!
    </p>
    
    <a href="/"><%= image_tag "started_banner.gif" %></a>
    
  </div>

</div>
  

app/views/playlist/edit.html.erb
<div class="mxtp-main">
        <%#= params if @debug = true %>
        <h1 class="playlist-title"><%= @title.upcase %></h1>

        <% if @playlist.title == nil %>
                <div class="mxtp-section">
			<%= form_tag("", method: "get", class: "playlist_title-form") do %>
				<%= text_field(:playlist, :title, class: "mxtp-form-input", placeholder: "click to change title" ) %>
				<p><%= submit_tag("Set Title", class: "mxtp-form-btn") %></p>
			<% end %>
                </div>
        <% end %>

	<h3 class="mxtp-labels">Profile Style</h3>
        <div class="mxtp-section">
		<%= form_tag("", method: "get", style: "playlist_style-form") do %> 
			<%= label_tag(:bgcolor, "Background Colour") %>
			<%= color_field(:style, :bgcolor) %> 
			<%= label_tag(:color, "Font Colour") %>
			<%= color_field(:style, :color) %> 
			<p><%= submit_tag("Update", class: "mxtp-form-btn") %></p>
		<% end %>
        </div>


    <h3 class="mxtp-labels">Songs</h3>
        <h4 class="mxtp-section">Keep adding songs until you're done...</h4>
        <div class="mxtp-section">
		<%= form_tag("", method: "get", style: "song_new-form") do %>
			<%#= label_tag(:song_title, "Song Title:") %>
			<%= text_field(:new_song, :song_title, class: "mxtp-form-input", placeholder: "song title") %>
			<p><%= submit_tag("Add", class: "mxtp-form-btn") %></p>
		<% end %>
        </div>

        <div class="mxtp-section song-list">
		<% for song in @songs %>
			<p>
				<%= "#{song.song_title} by #{song.artist_name}" %>
				<%= form_for :fix_artist, url:edit_playlist_song_path(song), method: :get do |fix_artist_form| %>
					<%= hidden_field_tag(:song_id, song.id) %>
					<%= fix_artist_form.submit "Fix Artist", class: "mxtp-form-sml-btn" %>	
				<% end %>
			</p>
		<% end %>
        </div>

        <div class="mxtp-section mxtp-buttons">
      		<%= button_to "Done!", playlist_path(@playlist), method: :get %>
      		<%= button_to "Delete Playlist", playlist_path(@playlist), method: :delete, class: "mxtp-form-red-btn" %>
        </div>
</div>

app/views/playlist/index.html.erb
<div class="main-background">

<div class="mxtp-main">

        <div class="mxtp-section">
                <div class="engage-section">
                        <h2 class="engage-title">CREATE A NEW PLAYLIST</h2>
                        <%= button_to "GET STARTED", new_playlist_path, method: "get" %>
                </div>
        </div>

<img src="" alt="">

</div>

</div>

app/views/playlist/show.html.erb
<div class="mxtp-main">
        <h1 class="playlist-title"><%= @playlist.title.upcase %></h1>

        <div class="cassette-tape"><%= image_tag("cassette.svg") %></div>

        <div class="mxtp-player">
            <iframe src="https://embed.spotify.com/?uri=spotify:trackset:PREFEREDTITLE:<%= @list_of_songs %>" frameborder="0" allowtransparency="true"></iframe>
        </div>

        <div class="mxtp-section">
                <% for song in @songs %>
                        <div class="song-listing">

                                <div class="song-details"><p><%= song.song_title %> by <%= song.artist_name %></p></div>
                                <!-- <div class="song-artist"><p>Artist: <%= song.artist_name %></p></div> -->
                                <div class="song-note-form">
                                <% if song.notes != nil %>
                                <div class="song-notes"><p><%= song.notes %></p></div>
                                <% else %>
                                  <%= form_for(song) do %>
                                    <%#= label_tag "Add Note:" %>
                                    <div class="mxtp-form-text"><%= text_area_tag :notes, "#{song.notes}" %></div>
                                    <%= submit_tag "Add Note", class: "mxtp-form-btn" %>
                                  <% end %>
                                <% end %>
                            <!-- <div class="mxtp-buttons"> -->
                                    <%= button_to "Delete Song", playlist_song_path(song), method: :delete, class: "mxtp-form-sml-btn-red" %>
                            <!-- </div> -->
                                </div>
                        </div>

                <% end %>
        </div>

        <div class="mxtp-section mxtp-buttons">
		<%= button_to "Edit Playlist", edit_playlist_path(@playlist), method: :get %>
		<%= button_to "Home", root_path, method: :get, class: "mxtp-form-red-btn" %>
        </div>

        <!-- 
        <iframe src="https://embed.spotify.com/?uri=spotify:track:3eMDxLX9JaTTIqyvk7rPfW" frameborder="0" allowtransparency="true"></iframe> -->
</div>